## Migration file generation.
## Generates SQL migration files with sequential numbering
## from detected schema changes.

import std/[os, strutils]
import ast, ddl, migration_diff

proc generateColumnDef(field: DootNode): string =
  ## Generates a column definition for ALTER TABLE ADD COLUMN.
  ## Same as generateFieldDDL but without trailing comma considerations.
  result = field.fieldName & " " & mapFieldType(field.fieldType)
  if isRequired(field):
    result &= " NOT NULL"
  result &= getDefaultValue(field)

proc generateMigrationSQL*(change: SchemaChange): string =
  ## Produces the SQL statement(s) for a single schema change.
  case change.kind
  of AddTable:
    result = generateDDL(change.addTableNode)
  of DropTable:
    result = "DROP TABLE " & change.dropTableName & ";"
  of AddColumn:
    let colDef = generateColumnDef(change.addColField)
    result = "ALTER TABLE " & change.addColTable & " ADD COLUMN " & colDef & ";"
  of DropColumn:
    result = "ALTER TABLE " & change.dropColTable & " DROP COLUMN " & change.dropColName & ";"
  of ChangeColumnType:
    # For SQLite, type changes require recreate-table pattern
    # Generate a comment noting this is a type change
    result = "-- Change column type: " & change.changeColTable & "." &
             change.changeColName & " from " & change.changeColOldType &
             " to " & change.changeColNewType & "\n"
    result &= "-- SQLite does not support ALTER COLUMN. Manual migration required.\n"
    result &= "-- Steps: CREATE new table, copy data, DROP old table, RENAME new table."

proc generateDescription(change: SchemaChange): string =
  ## Generates a human-readable description for migration filename.
  case change.kind
  of AddTable:
    result = "create_" & change.addTableNode.tableName
  of DropTable:
    result = "drop_" & change.dropTableName
  of AddColumn:
    result = "add_" & change.addColField.fieldName & "_to_" & change.addColTable
  of DropColumn:
    result = "drop_" & change.dropColName & "_from_" & change.dropColTable
  of ChangeColumnType:
    result = "change_" & change.changeColName & "_type_in_" & change.changeColTable

proc getNextMigrationNumber*(migrationsDir: string): int =
  ## Determines the next migration number by scanning existing files.
  ## Returns 1 if no migrations exist.
  result = 1
  if not dirExists(migrationsDir):
    return
  for kind, path in walkDir(migrationsDir):
    if kind == pcFile:
      let filename = extractFilename(path)
      if filename.endsWith(".sql"):
        # Extract the number prefix (first 3 chars)
        let prefix = filename[0..2]
        try:
          let num = parseInt(prefix)
          if num >= result:
            result = num + 1
        except ValueError:
          discard

proc generateMigrationFile*(changes: seq[SchemaChange], migrationsDir: string,
                            nextNumber: int = 0): string =
  ## Generates a migration file containing SQL for all changes.
  ## Returns the filename of the generated migration.
  ## If nextNumber is 0, auto-detects from existing files.
  if changes.len == 0:
    return ""

  # Determine the migration number
  var num = nextNumber
  if num == 0:
    num = getNextMigrationNumber(migrationsDir)

  # Generate description from changes
  var description: string
  if changes.len == 1:
    description = generateDescription(changes[0])
  else:
    # Use first change description as primary
    description = generateDescription(changes[0])
    if changes.len > 1:
      description &= "_and_more"

  # Build filename with zero-padded number
  let numStr = align($num, 3, '0')
  let filename = numStr & "_" & description & ".sql"

  # Generate SQL content
  var sqlContent = "-- Migration: " & filename & "\n"
  sqlContent &= "-- Generated by Doot migration engine\n\n"
  for i, change in changes:
    sqlContent &= generateMigrationSQL(change)
    if i < changes.len - 1:
      sqlContent &= "\n\n"
  sqlContent &= "\n"

  # Ensure migrations directory exists
  createDir(migrationsDir)

  # Write the file
  let filepath = migrationsDir / filename
  writeFile(filepath, sqlContent)

  return filename
